jobs:
  approve:
    if: github.event.pull_request.user.login == 'renovate[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/auto-approve-action@v3
        with:
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN_MARTIN }}

  enable-auto-merge:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: alexwilson/enable-github-automerge-action@main
        with:
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN_MARTIN }}

on:
  pull_request_target:
    types:
      - opened
      - ready_for_review
      - reopened
